---
spec/spec_helper_acceptance.rb:
  unmanaged: false
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
    - parameter_types
.github/workflows/ci.yml:
  with:
    beaker_facter: 'pe_status_check_role:PE-Role:primary'
spec/spec_helper.rb:
  facterdb_string_keys: true
